#!/bin/bash -e

echo "----> Building with Maven"
mvn package -DskipTests

echo "----> Uploading to Minecraft Server"
scp target/everything-bucket*.jar home.testdouble.com:~/Documents/bukkit_server/plugins

echo "----> Deploy complete! Type '/reload' in the game console to test your plugin"
